name: bitnet-rs-template
services:
  bitnet-rs-template:
    hostname: bitnet-rs-template
    container_name: bitnet-rs-template
    image: ghcr.io/rust-lang/rust:nightly
    restart: no
    volumes:
    - ..:/app/BitNet-Minimal
    environment:
    - CC=/usr/bin/clang-18
    - CXX=/usr/bin/clang++-18
    entrypoint: /app/BitNet-Minimal/.devcontainer/setup_env.sh
    